language: php

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 7.1
      sudo: true
      env:
        - DEPENDENCIES=""
        - EXECUTE_CS_CHECK=true
        - TEST_COVERAGE=true
    - php: 7.1
      sudo: true
      env:
        - DEPENDENCIES="--prefer-lowest --prefer-stable"

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local

before_script:
  - composer self-update
  - composer update --prefer-source $DEPENDENCIES

script:
  - cp phpunit.xml.$DRIVER phpunit.xml
  - ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/php-cs-fixer fix -v --diff --dry-run; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/docheader check src/ tests/; fi

after_success:
  - if [[ $TEST_COVERAGE == 'true' ]]; then php vendor/bin/coveralls -v; fi
  
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/61c75218816eebde4486
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
